<?php
/**
 * Minimal MCP (Model Context Protocol) server for Keystone Dashboard
 * Layout's code examples — pure request/response, no persistent
 * process and no SSE, so it runs on ordinary PHP-FPM/Apache shared
 * hosting. Speaks MCP's "Streamable HTTP" transport in its simplest,
 * fully-synchronous form: one JSON-RPC request in, one JSON-RPC
 * response out, `Content-Type: application/json` — the spec allows
 * this instead of an event stream, and a single POST per tool call is
 * all a docs-lookup tool ever needs.
 *
 * Data comes from examples-index.json, generated by build-index.mjs
 * (run locally/CI, never on this host) from the real, current example
 * source in the astro-docs and angular-examples-app trees — this file
 * never re-derives or guesses example content itself, only serves
 * what that script already extracted.
 *
 * Deploy: upload this file and examples-index.json to the same
 * directory on your PHP host, then point an MCP client at
 * https://<your-domain>/mcp.php as a remote/HTTP MCP server.
 */

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
  http_response_code(204);
  exit;
}

function jsonRpcResponse($id, $result = null, $error = null) {
  $payload = ['jsonrpc' => '2.0', 'id' => $id];
  if ($error !== null) {
    $payload['error'] = $error;
  } else {
    $payload['result'] = $result;
  }
  echo json_encode($payload);
  exit;
}

$indexPath = __DIR__ . '/examples-index.json';
$rawInput = file_get_contents('php://input');
$input = json_decode($rawInput, true);

if (!is_array($input) || !isset($input['method'])) {
  jsonRpcResponse(null, null, ['code' => -32600, 'message' => 'Invalid Request']);
}

$id = $input['id'] ?? null;
$method = $input['method'];

// Loaded once per request, never cached across requests — a plain
// PHP process has no long-lived state to cache it in anyway, and this
// file is small enough (real example source for 159 examples) that
// re-reading it per request is not worth the complexity of a cache
// layer on typical shared hosting.
function loadIndex($indexPath) {
  if (!file_exists($indexPath)) return [];
  $data = json_decode(file_get_contents($indexPath), true);
  return is_array($data) ? $data : [];
}

switch ($method) {
  case 'initialize':
    jsonRpcResponse($id, [
      'protocolVersion' => '2025-03-26',
      'capabilities' => ['tools' => ['listChanged' => false]],
      'serverInfo' => ['name' => 'kdl-examples', 'version' => '1.0.0'],
    ]);
    break;

  case 'notifications/initialized':
    // Notifications carry no `id` and expect no response body at all
    // — respond with an empty 202 rather than a JSON-RPC payload, per
    // spec, so a client doesn't misread this as a real result.
    http_response_code(202);
    exit;

  case 'tools/list':
    jsonRpcResponse($id, [
      'tools' => [
        [
          'name' => 'search_examples',
          'description' => 'Search Keystone Dashboard Layout code examples by keyword (matches title/description). Returns matching examples without their full source — call get_example with the returned slug+framework to fetch the real code.',
          'inputSchema' => [
            'type' => 'object',
            'properties' => [
              'query' => ['type' => 'string', 'description' => 'Keyword(s) to search for, e.g. "drag handle" or "undo redo"'],
              'framework' => ['type' => 'string', 'enum' => ['vue', 'react', 'angular'], 'description' => 'Optional — restrict to one framework'],
            ],
            'required' => ['query'],
          ],
        ],
        [
          'name' => 'get_example',
          'description' => 'Fetch the full, real source code for one example by framework + slug (as returned by search_examples).',
          'inputSchema' => [
            'type' => 'object',
            'properties' => [
              'framework' => ['type' => 'string', 'enum' => ['vue', 'react', 'angular']],
              'slug' => ['type' => 'string'],
            ],
            'required' => ['framework', 'slug'],
          ],
        ],
        [
          'name' => 'list_examples',
          'description' => 'List every available example (title + slug + framework), optionally filtered by framework. Use this to browse when you don\'t have a specific keyword yet.',
          'inputSchema' => [
            'type' => 'object',
            'properties' => [
              'framework' => ['type' => 'string', 'enum' => ['vue', 'react', 'angular']],
            ],
          ],
        ],
      ],
    ]);
    break;

  case 'tools/call':
    $params = $input['params'] ?? [];
    $name = $params['name'] ?? '';
    $args = $params['arguments'] ?? [];
    $index = loadIndex($indexPath);

    if ($name === 'search_examples') {
      $query = strtolower(trim($args['query'] ?? ''));
      $framework = $args['framework'] ?? null;
      if ($query === '') {
        jsonRpcResponse($id, null, ['code' => -32602, 'message' => 'query is required']);
      }
      $matches = array_values(array_filter($index, function ($e) use ($query, $framework) {
        if ($framework && $e['framework'] !== $framework) return false;
        $haystack = strtolower($e['title'] . ' ' . $e['description'] . ' ' . $e['slug']);
        return strpos($haystack, $query) !== false;
      }));
      // Summaries only — no `code` field — so a broad search doesn't
      // dump megabytes of source into the model's context; the client
      // calls get_example for the one(s) it actually wants.
      $summaries = array_map(fn($e) => [
        'framework' => $e['framework'], 'slug' => $e['slug'], 'title' => $e['title'],
        'description' => $e['description'], 'docsUrl' => $e['docsUrl'],
      ], $matches);
      jsonRpcResponse($id, ['content' => [['type' => 'text', 'text' => json_encode($summaries)]]]);
    } elseif ($name === 'get_example') {
      $framework = $args['framework'] ?? null;
      $slug = $args['slug'] ?? null;
      $found = null;
      foreach ($index as $e) {
        if ($e['framework'] === $framework && $e['slug'] === $slug) { $found = $e; break; }
      }
      if (!$found) {
        jsonRpcResponse($id, ['content' => [['type' => 'text', 'text' => 'No example found for that framework/slug.']]], null);
      } else {
        jsonRpcResponse($id, ['content' => [['type' => 'text', 'text' => json_encode($found)]]]);
      }
    } elseif ($name === 'list_examples') {
      $framework = $args['framework'] ?? null;
      $list = array_values(array_map(
        fn($e) => ['framework' => $e['framework'], 'slug' => $e['slug'], 'title' => $e['title']],
        array_filter($index, fn($e) => !$framework || $e['framework'] === $framework)
      ));
      jsonRpcResponse($id, ['content' => [['type' => 'text', 'text' => json_encode($list)]]]);
    } else {
      jsonRpcResponse($id, null, ['code' => -32601, 'message' => "Unknown tool: $name"]);
    }
    break;

  default:
    jsonRpcResponse($id, null, ['code' => -32601, 'message' => "Method not found: $method"]);
}
