import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import vue from '@astrojs/vue';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';

// Standalone Astro + Starlight site. Not part of the pnpm workspace on
// purpose (see package.json's own description) — installs/runs
// independently of the monorepo's turbo pipeline.
//
// Vue, React, and Angular all have real sidebar entries now. Each
// underlying package (packages/vue, packages/react, packages/angular)
// was confirmed directly (not assumed) to be a complete, tested,
// full-parity implementation before its docs began — every phase in
// each one's own docs/IMPLEMENTATION_PLAN.md is marked done — so each
// is being built out for real, the same incremental way (Guide first,
// then Features/Components/API/Examples).
//
// Angular examples specifically are NOT embedded here as Astro islands
// — that was tried via the community @analogjs/astro-angular package
// (there's no official @astrojs/angular) and abandoned after hitting
// real, unresolved issues (a component that consistently resolved to
// undefined in Astro's MDX renderer, even after fixing a genuine
// Angular-version mismatch and a genuine tsconfig scoping gap). Nor are
// they iframed — also tried, and reverted in favor of the simplest
// option: each of the 53 examples in this sidebar's own Angular
// "Examples" section links directly out to the real, deployed app at
// https://kdla.winnem.tech (angular-examples-app's own main.ts uses
// plain HTML5 path-based routing, NOT withHashLocation() — confirmed
// directly against that file's own current source, which documents
// this exact sidebar as the reason: a direct load of a deep route like
// /examples/01-basic-drag-resize needs to resolve to a real page for
// these links to work, which hash routing can't give a search engine
// or a plain <a href> new-tab open, only client-side navigation within
// the app itself. That app's own host in turn needs a standard SPA-
// fallback rewrite rule — see main.ts's own comment for what that
// means and why it's no longer optional now that hash routing is gone).
export default defineConfig(({ command }) => {
  // Same dev-vs-prod split as Header.astro's own ANGULAR_NAV_LINKS
  // (confirmed directly against that file's real source) — kept
  // consistent here rather than reusing `import.meta.env.DEV`, which
  // only works inside Vite-processed component code, not in this plain
  // Node config file; `command` (from defineConfig's own function
  // form) is the equivalent signal available here: `'dev'` for `astro
  // dev`, `'build'`/`'preview'` otherwise.
  const ANGULAR_EXAMPLES_APP_URL = command === 'dev' ? `http://localhost:4200` : `https://kdla.winnem.tech`;

  return {
  // Confirmed production domain: https://kdl.winnem.tech — unlocks three
  // separate, previously-missing pieces of SEO infrastructure, confirmed
  // directly against Starlight's own source/changelog, not assumed:
  //   1. Sitemap generation — Starlight does NOT generate a sitemap on
  //      its own; the separate `@astrojs/sitemap` integration (already
  //      a dependency, now wired in below) is required. `site` only
  //      unlocks canonical URLs and og:url (see #2/#3) — verified via a
  //      real build producing no sitemap-index.xml before this was
  //      added.
  //   2. Canonical URLs (`<link rel="canonical">`) — Starlight's own
  //      fixed bug report (withastro/starlight PR #3496) confirms it
  //      silently omitted this tag entirely from every page when `site`
  //      was unset, rather than emitting a wrong one.
  //   3. `<meta property="og:url">` — omitted for the identical reason,
  //      confirmed in the same source.
  // `public/robots.txt`'s own Sitemap: line uses this same domain — keep
  // both in sync if this ever changes.
  site: 'https://kdl.winnem.tech',
  integrations: [
    vue(),
    react(),
    sitemap(),
    starlight({
      title: 'Keystone Dashboard Layout',
      favicon: '/favicon.svg',
      // Route data middleware adding og:image/twitter:image meta tags
      // (pointing at the per-page images generated by
      // src/pages/og/[...slug].ts, via astro-og-canvas) and JSON-LD
      // structured data (TechArticle, BreadcrumbList, and
      // SoftwareSourceCode on the three framework home pages) to every
      // page — both entirely missing before this was added.
      //
      // Implemented as a `Head` component override (below, in
      // `components:`), NOT as `routeMiddleware` — that option doesn't
      // exist on the actually-installed @astrojs/starlight@0.30.6
      // (confirmed via a real, failed `astro build` run: "Unrecognized
      // key(s) in object: 'routeMiddleware'" — that option was only
      // added in Starlight 0.32). Upgrading to get it was deliberately
      // rejected: 0.32 also moves route data from `Astro.props` to
      // `Astro.locals.starlightRoute`, which would break this project's
      // other two overrides below (Sidebar/Header), both of which read
      // `Astro.props` by their own explicit, documented design against
      // this same installed version.
      // See `src/components/overrides/Head.astro`'s own header comment
      // for the full rationale.
      // Site-wide --kg-* design tokens (colors, fonts) used throughout
      // every ported example's own harness/decorative CSS. Without this,
      // only the custom landing page (index.astro, which pulls the same
      // file in via its own inline <style> @import) ever saw these
      // variables — every Starlight-rendered page, including every
      // example, silently fell back to unstyled/transparent values for
      // anything using var(--kg-*), since the custom property was never
      // actually defined there at all.
      customCss: ['./src/styles/tokens.css'],
      // Disabled site-wide rather than per-page — no page in this docs
      // site (guides, component reference, generated API, examples
      // alike) needs a right-hand heading outline badly enough to
      // justify the column width it reserves.
      tableOfContents: false,
      components: {
        // Adds og:image/twitter:image and JSON-LD to every page — see
        // this option's own comment above and the override file's own
        // header comment for why this is a `Head` override rather than
        // `routeMiddleware`.
        Head: './src/components/overrides/Head.astro',
        // Shows only the relevant top-level section in the sidebar
        // while browsing under it (Guide, Components, API, Examples) —
        // see the override file's own comment for why this couldn't
        // just follow Starlight's current "Multiple sidebars" example
        // verbatim (that example targets a newer Starlight version's
        // route-data API than what's installed here).
        Sidebar: './src/components/overrides/Sidebar.astro',
        // VitePress-style top nav (section links + a custom icon row,
        // since Starlight's own SocialIcons has no npm entry in its
        // supported platform list) — see that override's own comment
        // for the desktop-only caveat.
        Header: './src/components/overrides/Header.astro',
      },
      social: {
        github: 'https://github.com/gwinnem/keystone-dashboard-layout',
      },
      sidebar: [
        {
          label: 'Vue',
          items: [
            {
              label: 'Guide',
              items: [
                { label: 'Introduction', slug: 'vue/guide/introduction' },
                { label: 'Installation', slug: 'vue/guide/installation' },
                { label: 'Troubleshooting & FAQ', slug: 'vue/guide/troubleshooting' },
                {
                  label: 'Migrating from vue-grid-layout',
                  slug: 'vue/guide/migrating-from-vue-grid-layout',
                },
                {
                  label: 'Project',
                  items: [
                    { label: 'Architecture', slug: 'vue/guide/project/architecture' },
                    { label: 'Testing philosophy', slug: 'vue/guide/project/testing' },
                    { label: 'Accessibility scope', slug: 'vue/guide/project/accessibility' },
                    { label: 'Comparison: alternatives', slug: 'vue/guide/project/comparison-alternatives' },
                    { label: 'Comparison: commercial', slug: 'vue/guide/project/comparison-commercial' },
                    { label: 'Roadmap', slug: 'vue/guide/project/roadmap' },
                    { label: 'Production readiness', slug: 'vue/guide/project/production-readiness' },
                  ],
                },
                { label: 'Changelog', slug: 'vue/guide/changelog' },
              ],
            },
            { label: 'Features', slug: 'vue/features' },
            {
              label: 'Components',
              items: [
                { label: 'Overview', slug: 'vue/components' },
                {
                  label: 'GridLayout',
                  items: [
                    { label: 'Props', slug: 'vue/components/grid-layout/props' },
                    { label: 'Vue events', slug: 'vue/components/grid-layout/vue-events' },
                    { label: 'Eventbus events', slug: 'vue/components/grid-layout/eventbus-events' },
                    { label: 'Slots', slug: 'vue/components/grid-layout/slots' },
                  ],
                },
                {
                  label: 'GridItem',
                  items: [
                    { label: 'Props', slug: 'vue/components/grid-item/props' },
                    { label: 'Vue events', slug: 'vue/components/grid-item/vue-events' },
                    { label: 'Eventbus events', slug: 'vue/components/grid-item/eventbus-events' },
                    { label: 'Slots', slug: 'vue/components/grid-item/slots' },
                  ],
                },
                { label: 'CustomCloseButton', slug: 'vue/components/custom-close-button' },
                { label: 'CustomDragElement', slug: 'vue/components/custom-drag-element' },
                {
                  label: 'Styling',
                  items: [
                    { label: 'CSS variables', slug: 'vue/components/styling/css-variables' },
                    { label: 'GridLayout CSS', slug: 'vue/components/styling/css-grid-layout' },
                    { label: 'GridItem CSS', slug: 'vue/components/styling/css-grid-item' },
                  ],
                },
              ],
            },
            {
              label: 'API',
              items: [
                { label: 'Overview', slug: 'vue/api' },
                { label: 'Eventbus (IEventsData)', slug: 'vue/api/interfaces/eventbus' },
                { label: 'Layout interface', slug: 'vue/api/interfaces/layout' },
                { label: 'ARIA labels', slug: 'vue/api/interfaces/aria-labels' },
                { label: 'Pluggable compaction', slug: 'vue/api/interfaces/compactor' },
                { label: 'Layout persistence', slug: 'vue/api/interfaces/layout-persistence' },
                { label: 'SVG export & outside-drop payload', slug: 'vue/api/interfaces/svg-export-and-payload' },
                { label: 'Cross-grid & outside-drop event payloads', slug: 'vue/api/interfaces/event-payloads' },
                { label: 'Exposed instance state', slug: 'vue/api/interfaces/exposed-state' },
                { label: 'Layout types', slug: 'vue/api/types/layout' },
                { label: 'EGridLayoutEvent', slug: 'vue/api/enums/grid-layout-events' },
                { label: 'EGridItemEvent', slug: 'vue/api/enums/grid-item-events' },
                { label: 'ECompactType', slug: 'vue/api/enums/compact-type' },
              ],
            },
            {
              label: 'Examples',
              items: [
                { label: 'Gallery', slug: 'vue/examples' },
                // All 45 examples are now ported — see PLAN.md's own
                // §4.4 table for the full title/slug list.
                { label: '01 — Basic drag & resize', slug: 'vue/examples/basic-drag-resize' },
                { label: '02 — Bounded drag to container', slug: 'vue/examples/bounded-drag' },
                { label: '03 — Events', slug: 'vue/examples/events' },
                { label: '04 — Multiple grids', slug: 'vue/examples/multiple-grids' },
                { label: '05 — Drag allow / ignore elements', slug: 'vue/examples/drag-allow-ignore-elements' },
                { label: '06 — Mirrored (RTL)', slug: 'vue/examples/mirrored-rtl' },
                { label: '07 — Responsive breakpoints', slug: 'vue/examples/responsive-breakpoints' },
                { label: '08 — Prevent collision', slug: 'vue/examples/prevent-collision' },
                { label: '09 — Responsive predefined layouts', slug: 'vue/examples/responsive-predefined-layouts' },
                { label: '10 — Add or remove items', slug: 'vue/examples/add-remove-items' },
                { label: '11 — Drag, drop from outside', slug: 'vue/examples/outside-drag-drop' },
                { label: '12 — Drag, drop from grid to grid', slug: 'vue/examples/cross-grid-drag-drop' },
                { label: '13 — Show close button', slug: 'vue/examples/close-button' },
                { label: '14 — Border radius', slug: 'vue/examples/border-radius' },
                { label: '15 — Horizontal shift', slug: 'vue/examples/horizontal-shift' },
                { label: '16 — Show grid lines', slug: 'vue/examples/grid-lines' },
                { label: '17 — Static items', slug: 'vue/examples/static-items' },
                { label: '18 — Custom drag handle & close button', slug: 'vue/examples/custom-drag-handle-close-button' },
                { label: '19 — v-model & save/load layout', slug: 'vue/examples/save-load-layout' },
                { label: '20 — Auto-size grid on content', slug: 'vue/examples/auto-size-grid' },
                { label: '21 — Edit mode toggle', slug: 'vue/examples/edit-mode-toggle' },
                { label: '22 — Cross-grid drop restrictions', slug: 'vue/examples/cross-grid-drop-restrictions' },
                { label: '23 — Drag, drop from outside into multiple grids', slug: 'vue/examples/outside-drag-drop-multiple-grids' },
                { label: '24 — Configurable transition duration & easing', slug: 'vue/examples/transition-duration-easing' },
                { label: '25 — Custom drag-placeholder content', slug: 'vue/examples/custom-drag-placeholder' },
                { label: '26 — Alignment guides while dragging', slug: 'vue/examples/alignment-guides' },
                { label: '27 — scrollToItem & focusItem', slug: 'vue/examples/scroll-to-item-focus-item' },
                { label: '28 — Export layout as SVG', slug: 'vue/examples/svg-export' },
                { label: '29 — compactNow, rearrange & duplicateItem', slug: 'vue/examples/compact-now-rearrange-duplicate-item' },
                { label: '30 — Blocked-move feedback', slug: 'vue/examples/blocked-move-feedback' },
                { label: '31 — Per-item autoHeight', slug: 'vue/examples/per-item-auto-height' },
                { label: '32 — Snap to grid', slug: 'vue/examples/snap-to-grid' },
                { label: '33 — Configurable resize-hint appearance', slug: 'vue/examples/resize-hint-appearance' },
                { label: '34 — outsideDropAccept & readOutsideDropPayload', slug: 'vue/examples/outside-drop-accept-payload' },
                { label: '35 — Named layout presets', slug: 'vue/examples/named-presets' },
                { label: '36 — Localizable ARIA strings', slug: 'vue/examples/aria-labels' },
                { label: '37 — Multi-select & group move/resize', slug: 'vue/examples/multi-select-group-move-resize' },
                { label: '38 — Size constraints & aspect ratio', slug: 'vue/examples/size-constraints-aspect-ratio' },
                { label: '39 — autoScroll', slug: 'vue/examples/auto-scroll' },
                { label: '40 — Layout lifecycle events', slug: 'vue/examples/layout-lifecycle-events' },
                { label: '41 — Layout bounds & rendering options', slug: 'vue/examples/layout-bounds-rendering-options' },
                { label: '42 — Pluggable compaction', slug: 'vue/examples/pluggable-compaction' },
                { label: '43 — Undo/redo', slug: 'vue/examples/undo-redo' },
                { label: '44 — Grid dimensions', slug: 'vue/examples/grid-dimensions' },
                { label: '45 — Switching layouts & forcing a remount', slug: 'vue/examples/switching-layouts-remount' },
                // 46+ are new examples covering real features found
                // during the full documentation audit that had no
                // example in the original 45-example set (added to the
                // library after that set was authored) — see PLAN.md.
                { label: '46 — Align & distribute selected items', slug: 'vue/examples/align-distribute-selected' },
                { label: '47 — Spacing indicators', slug: 'vue/examples/spacing-indicators' },
                { label: '48 — Custom header slot', slug: 'vue/examples/custom-header-slot' },
                { label: '49 — Per-item zIndex override', slug: 'vue/examples/per-item-z-index' },
                { label: '50 — Height modes (heightMode)', slug: 'vue/examples/height-modes' },
                { label: '51 — Drag activation distance', slug: 'vue/examples/drag-activation-distance' },
                { label: '52 — Restricting resize handles to specific edges', slug: 'vue/examples/restrict-resize-handles' },
                { label: '53 — Resize direction toggles', slug: 'vue/examples/resize-direction-toggles' },
              ],
            },
          ],
        },
        // React docs, begun for real (packages/react is a complete,
        // tested, full-parity implementation, confirmed directly —
        // see astro.config.mjs's own top comment). Built out
        // incrementally, the same phase order Vue's own docs followed:
        // Guide first, then Features/Components/API/Examples.
        {
          label: 'React',
          items: [
            {
              label: 'Guide',
              items: [
                { label: 'Introduction', slug: 'react/guide/introduction' },
                { label: 'Installation', slug: 'react/guide/installation' },
                { label: 'Troubleshooting & FAQ', slug: 'react/guide/troubleshooting' },
                {
                  label: 'Migrating from react-grid-layout',
                  slug: 'react/guide/migrating-from-react-grid-layout',
                },
                {
                  label: 'Project',
                  items: [
                    { label: 'Architecture', slug: 'react/guide/project/architecture' },
                    { label: 'Testing philosophy', slug: 'react/guide/project/testing' },
                    { label: 'Accessibility scope', slug: 'react/guide/project/accessibility' },
                    { label: 'Comparison: alternatives', slug: 'react/guide/project/comparison-alternatives' },
                    { label: 'Comparison: commercial', slug: 'react/guide/project/comparison-commercial' },
                    { label: 'Roadmap', slug: 'react/guide/project/roadmap' },
                    { label: 'Production readiness', slug: 'react/guide/project/production-readiness' },
                  ],
                },
                { label: 'Changelog', slug: 'react/guide/changelog' },
              ],
            },
            { label: 'Features', slug: 'react/features' },
            {
              label: 'Components',
              items: [
                { label: 'Overview', slug: 'react/components' },
                { label: 'GridLayout props', slug: 'react/components/grid-layout/props' },
                { label: 'GridItem props', slug: 'react/components/grid-item/props' },
                { label: 'Styling', slug: 'react/components/styling' },
              ],
            },
            {
              label: 'API',
              items: [
                { label: 'Overview', slug: 'react/api' },
                { label: 'Imperative handle (IGridLayoutHandle)', slug: 'react/api/interfaces/imperative-handle' },
                { label: 'Layout interface', slug: 'react/api/interfaces/layout' },
                { label: 'ARIA labels', slug: 'react/api/interfaces/aria-labels' },
                { label: 'Pluggable compaction', slug: 'react/api/interfaces/compactor' },
                { label: 'Layout persistence', slug: 'react/api/interfaces/layout-persistence' },
                { label: 'SVG export & outside-drop payload', slug: 'react/api/interfaces/svg-export-and-payload' },
                { label: 'Cross-grid & outside-drop event payloads', slug: 'react/api/interfaces/event-payloads' },
                { label: 'Layout types', slug: 'react/api/types/layout' },
                { label: 'ECompactType', slug: 'react/api/enums/compact-type' },
              ],
            },
            {
              label: 'Examples',
              items: [
                { label: 'Gallery', slug: 'react/examples' },
                { label: '01 — Basic drag & resize', slug: 'react/examples/basic-drag-resize' },
                { label: '02 — Bounded drag to container', slug: 'react/examples/bounded-drag' },
                { label: '03 — Events', slug: 'react/examples/events' },
                { label: '04 — Multiple grids', slug: 'react/examples/multiple-grids' },
                { label: '05 — Drag allow / ignore elements', slug: 'react/examples/drag-allow-ignore-elements' },
                { label: '06 — Mirrored (RTL)', slug: 'react/examples/mirrored-rtl' },
                { label: '07 — Responsive breakpoints', slug: 'react/examples/responsive-breakpoints' },
                { label: '08 — Prevent collision', slug: 'react/examples/prevent-collision' },
                { label: '09 — Responsive predefined layouts', slug: 'react/examples/responsive-predefined-layouts' },
                { label: '10 — Add or remove items', slug: 'react/examples/add-remove-items' },
                { label: '11 — Drag, drop from outside', slug: 'react/examples/outside-drag-drop' },
                { label: '12 — Drag, drop from grid to grid', slug: 'react/examples/cross-grid-drag-drop' },
                { label: '13 — Show close button', slug: 'react/examples/close-button' },
                { label: '14 — Border radius', slug: 'react/examples/border-radius' },
                { label: '15 — Horizontal shift', slug: 'react/examples/horizontal-shift' },
                { label: '16 — Show grid lines', slug: 'react/examples/grid-lines' },
                { label: '17 — Static items', slug: 'react/examples/static-items' },
                { label: '18 — Custom drag handle & close button', slug: 'react/examples/custom-drag-handle-close-button' },
                { label: '19 — Save/load layout', slug: 'react/examples/save-load-layout' },
                { label: '20 — Auto-size grid on content', slug: 'react/examples/auto-size-grid' },
                { label: '21 — Edit mode toggle', slug: 'react/examples/edit-mode-toggle' },
                { label: '22 — Cross-grid drop restrictions', slug: 'react/examples/cross-grid-drop-restrictions' },
                { label: '23 — Drag, drop from outside into multiple grids', slug: 'react/examples/outside-drag-drop-multiple-grids' },
                { label: '24 — Configurable transition duration & easing', slug: 'react/examples/transition-duration-easing' },
                { label: '25 — Custom drag-placeholder content', slug: 'react/examples/custom-drag-placeholder' },
                { label: '26 — Alignment guides while dragging', slug: 'react/examples/alignment-guides' },
                { label: '27 — scrollToItem & focusItem', slug: 'react/examples/scroll-to-item-focus-item' },
                { label: '28 — Export layout as SVG', slug: 'react/examples/svg-export' },
                { label: '29 — compactNow, rearrange & duplicateItem', slug: 'react/examples/compact-now-rearrange-duplicate-item' },
                { label: '30 — Blocked-move feedback', slug: 'react/examples/blocked-move-feedback' },
                { label: '31 — Per-item autoHeight', slug: 'react/examples/per-item-auto-height' },
                { label: '32 — Snap to grid', slug: 'react/examples/snap-to-grid' },
                { label: '33 — Configurable resize-hint appearance', slug: 'react/examples/resize-hint-appearance' },
                { label: '34 — outsideDropAccept & readOutsideDropPayload', slug: 'react/examples/outside-drop-accept-payload' },
                { label: '35 — Named layout presets', slug: 'react/examples/named-presets' },
                { label: '36 — Localizable ARIA strings', slug: 'react/examples/aria-labels' },
                { label: '37 — Multi-select & group move/resize', slug: 'react/examples/multi-select-group-move-resize' },
                { label: '38 — Size constraints & aspect ratio', slug: 'react/examples/size-constraints-aspect-ratio' },
                { label: '39 — autoScroll', slug: 'react/examples/auto-scroll' },
                { label: '40 — Layout lifecycle events', slug: 'react/examples/layout-lifecycle-events' },
                { label: '41 — Layout bounds & rendering options', slug: 'react/examples/layout-bounds-rendering-options' },
                { label: '42 — Pluggable compaction', slug: 'react/examples/pluggable-compaction' },
                { label: '43 — Undo/redo', slug: 'react/examples/undo-redo' },
                { label: '44 — Grid dimensions', slug: 'react/examples/grid-dimensions' },
                { label: '45 — Switching layouts & forcing a remount', slug: 'react/examples/switching-layouts-remount' },
                { label: '46 — Align & distribute selected items', slug: 'react/examples/align-distribute-selected' },
                { label: '47 — Spacing indicators', slug: 'react/examples/spacing-indicators' },
                { label: '48 — Custom header', slug: 'react/examples/custom-header-slot' },
                { label: '49 — Per-item zIndex override', slug: 'react/examples/per-item-z-index' },
                { label: '50 — Height modes (heightMode)', slug: 'react/examples/height-modes' },
                { label: '51 — Drag activation distance', slug: 'react/examples/drag-activation-distance' },
                { label: '52 — Restricting resize handles to specific edges', slug: 'react/examples/restrict-resize-handles' },
                { label: '53 — Resize direction toggles', slug: 'react/examples/resize-direction-toggles' },
              ],
            },
          ],
        },
        // Angular docs, begun for real (packages/angular was
        // confirmed directly — via its own docs/IMPLEMENTATION_PLAN.md
        // and a full read of grid-layout.component.ts/grid-item.
        // component.ts — to be a complete, full-parity implementation,
        // matching Vue/React). Built out incrementally, the same phase
        // order Vue/React's own docs followed: Guide first, then
        // Features/Components/API/Examples.
        {
          label: 'Angular',
          items: [
            {
              label: 'Guide',
              items: [
                { label: 'Introduction', slug: 'angular/guide/introduction' },
                { label: 'Installation', slug: 'angular/guide/installation' },
                { label: 'Troubleshooting & FAQ', slug: 'angular/guide/troubleshooting' },
                {
                  label: 'Migrating from angular-gridster2',
                  slug: 'angular/guide/migrating-from-angular-gridster2',
                },
                {
                  label: 'Project',
                  items: [
                    { label: 'Architecture', slug: 'angular/guide/project/architecture' },
                    { label: 'Testing philosophy', slug: 'angular/guide/project/testing' },
                    { label: 'Accessibility scope', slug: 'angular/guide/project/accessibility' },
                    { label: 'Comparison: alternatives', slug: 'angular/guide/project/comparison-alternatives' },
                    { label: 'Comparison: commercial', slug: 'angular/guide/project/comparison-commercial' },
                    { label: 'Roadmap', slug: 'angular/guide/project/roadmap' },
                    { label: 'Production readiness', slug: 'angular/guide/project/production-readiness' },
                  ],
                },
                { label: 'Changelog', slug: 'angular/guide/changelog' },
              ],
            },
            { label: 'Features', slug: 'angular/features' },
            {
              label: 'Components',
              items: [
                { label: 'Overview', slug: 'angular/components' },
                { label: 'GridLayoutComponent props', slug: 'angular/components/grid-layout/props' },
                { label: 'GridItemComponent props', slug: 'angular/components/grid-item/props' },
              ],
            },
            {
              label: 'API',
              items: [
                { label: 'Overview', slug: 'angular/api' },
                { label: 'Public members (GridLayoutComponent)', slug: 'angular/api/interfaces/public-members' },
                { label: 'Layout persistence', slug: 'angular/api/interfaces/layout-persistence' },
                { label: 'Cross-grid & outside-drop event payloads', slug: 'angular/api/interfaces/event-payloads' },
              ],
            },
            {
              // All 53 examples live in a real, separate, standalone
              // Angular app (angular-examples-app), not as astro-docs
              // pages — every link below is external, using the same
              // dev-vs-prod ANGULAR_EXAMPLES_APP_URL this file's own top
              // comment explains. Labels/slugs copied verbatim from that
              // app's own sidebar (src/app/app.component.ts) rather than
              // retyped, so they can't drift out of sync with it.
              label: 'Examples',
              items: [
                { label: 'Gallery', link: `${ANGULAR_EXAMPLES_APP_URL}/` },
                { label: '01 — Basic drag & resize', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/01-basic-drag-resize` },
                { label: '02 — Bounded drag to container', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/02-bounded-drag` },
                { label: '03 — Events', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/03-events` },
                { label: '04 — Multiple grids', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/04-multiple-grids` },
                { label: '05 — Drag allow / ignore elements', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/05-drag-allow-ignore-elements` },
                { label: '06 — Mirrored (RTL)', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/06-mirrored-rtl` },
                { label: '07 — Responsive breakpoints', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/07-responsive-breakpoints` },
                { label: '08 — Prevent collision', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/08-prevent-collision` },
                { label: '09 — Responsive predefined layouts', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/09-responsive-predefined-layouts` },
                { label: '10 — Add or remove items', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/10-add-remove-items` },
                { label: '11 — Drag, drop from outside', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/11-outside-drag-drop` },
                { label: '12 — Drag, drop from grid to grid', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/12-cross-grid-drag-drop` },
                { label: '13 — Show close button', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/13-close-button` },
                { label: '14 — Border radius', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/14-border-radius` },
                { label: '15 — Horizontal shift', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/15-horizontal-shift` },
                { label: '16 — Show grid lines', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/16-grid-lines` },
                { label: '17 — Static items', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/17-static-items` },
                { label: '18 — Custom drag handle & close button', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/18-custom-drag-handle-close-button` },
                { label: '19 — Save/load layout', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/19-save-load-layout` },
                { label: '20 — Auto-size grid on content', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/20-auto-size-grid` },
                { label: '21 — Edit mode toggle', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/21-edit-mode-toggle` },
                { label: '22 — Cross-grid drop restrictions', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/22-cross-grid-drop-restrictions` },
                { label: '23 — Drag, drop from outside into multiple grids', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/23-outside-drag-drop-multiple-grids` },
                { label: '24 — Configurable transition duration & easing', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/24-transition-duration-easing` },
                { label: '25 — Custom drag-placeholder content', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/25-custom-drag-placeholder` },
                { label: '26 — Alignment guides while dragging', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/26-alignment-guides` },
                { label: '27 — scrollToItem & focusItem', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/27-scroll-to-item-focus-item` },
                { label: '28 — Export layout as SVG', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/28-svg-export` },
                { label: '29 — compactNow, rearrange & duplicateItem', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/29-compact-now-rearrange-duplicate-item` },
                { label: '30 — Blocked-move feedback', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/30-blocked-move-feedback` },
                { label: '31 — Per-item autoHeight', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/31-per-item-auto-height` },
                { label: '32 — Snap to grid', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/32-snap-to-grid` },
                { label: '33 — Configurable resize-hint appearance', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/33-resize-hint-appearance` },
                { label: '34 — outsideDropAccept & readOutsideDropPayload', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/34-outside-drop-accept-payload` },
                { label: '35 — Named layout presets', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/35-named-presets` },
                { label: '36 — Localizable ARIA strings', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/36-aria-labels` },
                { label: '37 — Multi-select & group move/resize', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/37-multi-select-group-move-resize` },
                { label: '38 — Size constraints & aspect ratio', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/38-size-constraints-aspect-ratio` },
                { label: '39 — autoScroll', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/39-auto-scroll` },
                { label: '40 — Layout lifecycle events', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/40-layout-lifecycle-events` },
                { label: '41 — Layout bounds & rendering options', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/41-layout-bounds-rendering-options` },
                { label: '42 — Pluggable compaction', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/42-pluggable-compaction` },
                { label: '43 — Undo/redo', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/43-undo-redo` },
                { label: '44 — Grid dimensions', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/44-grid-dimensions` },
                { label: '45 — Switching layouts & forcing a remount', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/45-switching-layouts-remount` },
                { label: '46 — Align & distribute selected items', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/46-align-distribute-selected` },
                { label: '47 — Spacing indicators', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/47-spacing-indicators` },
                { label: '48 — Custom header', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/48-custom-header-slot` },
                { label: '49 — Per-item zIndex override', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/49-per-item-z-index` },
                { label: '50 — Height modes (heightMode)', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/50-height-modes` },
                { label: '51 — Drag activation distance', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/51-drag-activation-distance` },
                { label: '52 — Restricting resize handles to specific edges', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/52-restrict-resize-handles` },
                { label: '53 — Resize direction toggles', link: `${ANGULAR_EXAMPLES_APP_URL}/examples/53-resize-direction-toggles` },
              ],
            },
          ],
        },
        // Core docs — the framework-agnostic shared implementation
        // underneath Vue/React/Angular, not a UI component library
        // itself, so this section deliberately doesn't follow the same
        // Guide/Features/Components/API/Examples shape the three
        // framework packages above use. Placed last since it's an
        // advanced/internals topic most users installing one of the
        // three framework packages never need to open at all (see this
        // section's own Introduction page for who it actually is for).
        {
          label: 'Core',
          items: [
            {
              label: 'Guide',
              items: [
                { label: 'Introduction', slug: 'core/guide/introduction' },
                { label: 'Installation', slug: 'core/guide/installation' },
              ],
            },
            {
              label: 'API reference',
              items: [
                { label: 'Overview', slug: 'core/api' },
                // Generated by scripts/generate-typedoc.mjs (wired as
                // predev/prebuild in package.json) directly from
                // packages/core's own exported TypeScript source —
                // autogenerate lists whatever that script wrote last,
                // no manual upkeep needed as the exported API grows.
                { label: 'Reference', autogenerate: { directory: 'core/api/reference' } },
              ],
            },
          ],
        },
      ],
    }),
  ],
  // The cross-origin isolation headers the StackBlitz "Playground" tab
  // needs (see ExampleTryIt.astro's own `playground` prop) are NOT set
  // here — `vite.server.headers` was tried first and confirmed directly
  // NOT to apply to Astro's own page-route responses (a real fetch()
  // against a rendered page showed none of the headers present, even
  // after a full dev-server restart). Set instead in
  // src/middleware.ts, which works uniformly across `astro dev`,
  // `astro preview`, and a real production deploy.
  };
});
